# Site settings
title: Houkibosi
description: 'Business Card Page'
url: 'http://houkibosi.com'
baseurl: ''
profilepic: '/images/houkibosi.jpg'
bkimage: '/images/bk2.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'd16bb15042.js'

author:
  name: 'jaymin lee'
  email: houkibosi486@gmail.com
  twitter_username: houkibosi
  facebook_username: houkibosi
  github_username:  houkibosi
  linkedin_username:  Jaymin LEE
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
